# Site settings
title: Gamestats
email: your-email@domain.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "o melhor programa para analisar suas estatisicas em games."
keywords: "your keywords, separated by commas"
skills: "Analise da estatiscas - Jogos ao vivo - pontos de equipes"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: UTFPR
  location: Localização 
  social: Criadores
  credits: Creditos

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Gabriel Dias
    url: https://www.instagram.com/gabadias1/
  - title: Felipe Salazar
    url: https://www.instagram.com/fesalazar21/
  - title: Rubens 
    url: https://www.instagram.com/rubensrff/
  - title: Marlus 
    url: https://www.instagram.com/0_marlus/
 

# Postal address (add as many lines as necessary)
address:
  - line: Paraná
  - line: Campo mourão

# Credits content
credits: 'Alunos da <a href="https://www.utfpr.edu.br/">UTFPR</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
